import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseClient, parsePallet } from '../schema.js';
import type { Client, Pallet } from '../types.js';

/**
 * The library as plain files in a folder.
 *
 * One JSON file per design, and one for the clients. This is the whole of the
 * persistence: there is no database, and the folder is expected to be one that
 * Google Drive syncs, so that four people on four laptops are working on the
 * same designs without any of them running a server.
 *
 * That setting is what shapes the rules below. A sync client copies files
 * whenever it likes, including while they are being written, and hands them
 * over half-downloaded. So every write lands by rename, which is atomic, and
 * every read tolerates a file that does not parse rather than taking the
 * dashboard down with it.
 *
 *   <root>/clients.json      every client
 *   <root>/designs/<id>.json one design
 *   <root>/backups/<stamp>/  a copy of both, taken at startup
 */

export const DESIGNS_DIR = 'designs';
export const CLIENTS_FILE = 'clients.json';

/** A file that could not be read. Reported, never thrown. */
export interface StoreProblem {
  file: string;
  reason: string;
}

/**
 * A parsed file, good only while the file on disk has not moved.
 *
 * The timestamp is in nanoseconds rather than milliseconds on purpose. Drive
 * writes files underneath a running program, and two writes in the same
 * millisecond that happen to be the same length would otherwise look like no
 * write at all — and the editor would go on serving the design as it was
 * before a colleague's change landed.
 */
interface Cached<T> {
  mtimeNs: bigint;
  size: bigint;
  value: T;
}

/** Size and modification time at the finest resolution the platform keeps. */
function fingerprint(path: string): { mtimeNs: bigint; size: bigint } {
  const stat = statSync(path, { bigint: true });
  return { mtimeNs: stat.mtimeNs, size: stat.size };
}

/**
 * What a design is called on disk.
 *
 * Ids are generated by `newId` and are UUIDs, so this is almost always the id
 * unchanged. The encoding is for anything that arrived from somewhere else:
 * percent-escaping is reversible and therefore cannot map two ids onto one
 * file, and it takes out the characters Windows will not accept in a name.
 *
 * Nothing ever decodes it. A design's id is read from inside the document,
 * which is where it is authoritative; the file name only has to be unique and
 * stable across saves.
 */
export function fileNameFor(id: string): string {
  const escaped = encodeURIComponent(id).replace(
    /[*'()!~]/g,
    (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`,
  );
  return `${escaped}.json`;
}

/** Write via a temporary file and a rename, so a reader never sees half of one. */
function writeAtomic(path: string, contents: string): void {
  const temp = `${path}.tmp-${process.pid.toString(36)}-${Date.now().toString(36)}`;
  try {
    writeFileSync(temp, contents, 'utf8');
    renameSync(temp, path);
  } catch (error) {
    rmSync(temp, { force: true });
    throw error;
  }
}

export class FileStore {
  readonly root: string;
  readonly designsDir: string;
  readonly clientsPath: string;

  /** Parsed designs, keyed by file name, kept only while the file is untouched. */
  private designCache = new Map<string, Cached<Pallet>>();
  private clientCache: Cached<Client[]> | undefined;

  /** Files that would not parse on the last read. */
  private problems: StoreProblem[] = [];

  /** Set while a transaction is open: reads see these before they see the disk. */
  private pending: { designs: Map<string, Pallet>; deletes: Set<string>; clients?: Client[] } | undefined;

  constructor(root: string) {
    this.root = resolve(root);
    this.designsDir = join(this.root, DESIGNS_DIR);
    this.clientsPath = join(this.root, CLIENTS_FILE);
    mkdirSync(this.designsDir, { recursive: true });
  }

  /** What could not be read last time the folder was listed. */
  lastProblems(): StoreProblem[] {
    return [...this.problems];
  }

  // -- clients ------------------------------------------------------------

  readClients(): Client[] {
    if (this.pending?.clients) return this.pending.clients;
    if (!existsSync(this.clientsPath)) return [];

    const mark = fingerprint(this.clientsPath);
    const cached = this.clientCache;
    if (cached && cached.mtimeNs === mark.mtimeNs && cached.size === mark.size) return cached.value;

    let value: Client[] = [];
    try {
      const raw = JSON.parse(readFileSync(this.clientsPath, 'utf8')) as unknown;
      value = (Array.isArray(raw) ? raw : []).map((entry) => parseClient(entry));
      this.problems = this.problems.filter((problem) => problem.file !== CLIENTS_FILE);
    } catch (error) {
      // The clients file is one file, and losing it would lose every client who
      // has no design yet. It is not worth taking the folder down for, but it
      // is worth saying loudly.
      this.note(CLIENTS_FILE, error);
      return this.clientCache?.value ?? [];
    }

    this.clientCache = { ...mark, value };
    return value;
  }

  writeClients(clients: Client[]): void {
    if (this.pending) {
      this.pending.clients = clients;
      return;
    }
    writeAtomic(this.clientsPath, `${JSON.stringify(clients, null, 2)}\n`);
    this.clientCache = undefined;
  }

  // -- designs ------------------------------------------------------------

  /**
   * Every design in the folder.
   *
   * A file that will not parse is left out and recorded. Drive may be part way
   * through downloading it, or somebody may have dropped something that is not
   * a design into the folder; neither is a reason for the dashboard to fail.
   */
  listDesigns(): Pallet[] {
    const found = new Map<string, Pallet>();
    const problems: StoreProblem[] = [];

    for (const name of this.designFiles()) {
      if (this.pending?.deletes.has(name)) continue;
      const staged = this.pending?.designs.get(name);
      if (staged) {
        found.set(name, staged);
        continue;
      }
      const design = this.readFile(name, problems);
      if (design) found.set(name, design);
    }

    for (const [name, design] of this.pending?.designs ?? []) found.set(name, design);

    this.problems = problems;
    if (problems.length > 0) {
      for (const problem of problems) {
        console.error(`Skipped ${problem.file}: ${problem.reason}`);
      }
    }
    return [...found.values()];
  }

  readDesign(id: string): Pallet | undefined {
    const name = fileNameFor(id);
    if (this.pending?.deletes.has(name)) return undefined;
    const staged = this.pending?.designs.get(name);
    if (staged) return staged;
    return this.readFile(name, []);
  }

  hasDesign(id: string): boolean {
    return this.readDesign(id) !== undefined;
  }

  writeDesign(design: Pallet): void {
    const name = fileNameFor(design.id);
    if (this.pending) {
      this.pending.designs.set(name, design);
      this.pending.deletes.delete(name);
      return;
    }
    writeAtomic(join(this.designsDir, name), `${JSON.stringify(design, null, 2)}\n`);
    this.designCache.delete(name);
  }

  deleteDesign(id: string): void {
    const name = fileNameFor(id);
    if (this.pending) {
      this.pending.designs.delete(name);
      this.pending.deletes.add(name);
      return;
    }
    rmSync(join(this.designsDir, name), { force: true });
    this.designCache.delete(name);
  }

  /**
   * Run a batch of writes, and apply them only if all of it succeeded.
   *
   * An import is the reason this exists: a library file that turns out to be
   * bad halfway through must leave the folder as it was, not half written. The
   * writes are held in memory and go to disk at the end, which is as close to a
   * transaction as a folder of files gets — and close enough, because the only
   * failure it has to survive is a bad document rather than a dying machine.
   */
  transaction<T>(run: () => T): T {
    if (this.pending) return run();

    this.pending = { designs: new Map(), deletes: new Set() };
    let staged;
    try {
      const result = run();
      staged = this.pending;
      return result;
    } finally {
      this.pending = undefined;
      if (staged) {
        for (const name of staged.deletes) {
          rmSync(join(this.designsDir, name), { force: true });
          this.designCache.delete(name);
        }
        for (const [name, design] of staged.designs) {
          writeAtomic(join(this.designsDir, name), `${JSON.stringify(design, null, 2)}\n`);
          this.designCache.delete(name);
        }
        if (staged.clients) this.writeClients(staged.clients);
      }
    }
  }

  // -- reading ------------------------------------------------------------

  private designFiles(): string[] {
    if (!existsSync(this.designsDir)) return [];
    return readdirSync(this.designsDir)
      .filter((name) => name.endsWith('.json'))
      .sort();
  }

  /** One design file, from the cache when the file has not moved since. */
  private readFile(name: string, problems: StoreProblem[]): Pallet | undefined {
    const path = join(this.designsDir, name);
    let mark;
    try {
      mark = fingerprint(path);
    } catch {
      return undefined;
    }

    const cached = this.designCache.get(name);
    if (cached && cached.mtimeNs === mark.mtimeNs && cached.size === mark.size) return cached.value;

    try {
      const value = parsePallet(JSON.parse(readFileSync(path, 'utf8')));
      this.designCache.set(name, { ...mark, value });
      return value;
    } catch (error) {
      this.designCache.delete(name);
      problems.push({ file: name, reason: error instanceof Error ? error.message : String(error) });
      return undefined;
    }
  }

  private note(file: string, error: unknown): void {
    const reason = error instanceof Error ? error.message : String(error);
    this.problems = [...this.problems.filter((problem) => problem.file !== file), { file, reason }];
    console.error(`Could not read ${file}: ${reason}`);
  }
}
