#!/usr/bin/env node
/**
 * Turn the logo and the company font into a TypeScript module of data URIs.
 *
 *   npm run brand
 *
 * The sheet is printed by handing one self-contained HTML string to a headless
 * browser, and the same string is opened in a tab by the editor. Neither has a
 * base URL to resolve a file path against, so the logo and the font have to
 * travel inside the document. Base64 in a committed module is the only form
 * that works in the browser bundle and under `tsx` alike.
 *
 * Run this again only when the artwork changes; the output is committed and the
 * originals are not needed to build or serve the tool.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');

/** The artwork, as supplied, in the project root. */
const SOURCES = {
  logo: { file: 'Ambica Patterns (india) Pvt.Ltd..png', mime: 'image/png' },
  font: { file: 'ITC Anna Regular.otf', mime: 'font/otf' },
} as const;

function dataUri(file: string, mime: string): string {
  const path = resolve(root, file);
  let bytes: Buffer;
  try {
    bytes = readFileSync(path);
  } catch {
    throw new Error(
      `Missing brand artwork: ${path}\n` +
        'Put the file back, or point SOURCES in src/brand/build.ts at the new one.',
    );
  }
  return `data:${mime};base64,${bytes.toString('base64')}`;
}

const logo = dataUri(SOURCES.logo.file, SOURCES.logo.mime);
const font = dataUri(SOURCES.font.file, SOURCES.font.mime);

const module = `// Generated by \`npm run brand\` from the artwork in the project root.
// Do not edit by hand: change the artwork and run the script again.

/** The logo, as a data URI, so a sheet carries it wherever it is opened. */
export const LOGO_DATA_URI =
  '${logo}';

/** The company font, as a data URI, for the @font-face rule on the sheet. */
export const BRAND_FONT_DATA_URI =
  '${font}';
`;

const out = resolve(here, 'assets.ts');
writeFileSync(out, module, 'utf8');
console.log(
  `Wrote ${out} — logo ${Math.round(logo.length / 1024)} kB, font ${Math.round(font.length / 1024)} kB (base64)`,
);
