#!/usr/bin/env node
/**
 * Turn the company font into a TypeScript module holding it as a data URI.
 *
 *   npm run brand
 *
 * The sheet is printed by handing one self-contained HTML string to a headless
 * browser, and the same string is opened in a tab by the editor. Neither has a
 * base URL to resolve a file path against, so the font has to travel inside the
 * document. Base64 in a committed module is the only form that works in the
 * browser bundle and under `tsx` alike.
 *
 * The logo is **not** here: it is traced to two paths in `logo.ts`, which is a
 * few hundred bytes instead of fifty kilobytes and leaves nothing raster in any
 * output. If the artwork changes, that file has to be re-measured by hand.
 *
 * Run this again only when the font changes; the output is committed and the
 * original is not needed to build or serve the tool.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');

/** The face, as supplied, in the project root. */
const SOURCES = {
  font: { file: 'ITC Anna Regular.otf', mime: 'font/otf' },
} as const;

function dataUri(file: string, mime: string): string {
  const path = resolve(root, file);
  let bytes: Buffer;
  try {
    bytes = readFileSync(path);
  } catch {
    throw new Error(
      `Missing brand artwork: ${path}\n` +
        'Put the file back, or point SOURCES in src/brand/build.ts at the new one.',
    );
  }
  return `data:${mime};base64,${bytes.toString('base64')}`;
}

const font = dataUri(SOURCES.font.file, SOURCES.font.mime);

const module = `// Generated by \`npm run brand\` from the font in the project root.
// Do not edit by hand: change the font and run the script again.
// The logo is not here — it is traced to paths in logo.ts.

/** The company font, as a data URI, for the @font-face rule on the sheet. */
export const BRAND_FONT_DATA_URI =
  '${font}';
`;

const out = resolve(here, 'assets.ts');
writeFileSync(out, module, 'utf8');
console.log(`Wrote ${out} — font ${Math.round(font.length / 1024)} kB (base64)`);
